"""Generate a reproducible TPC-H-derived educational data set with DuckDB dbgen.

This is data generation only, not an official or compliant TPC-H benchmark.
Run with the bundled Python; DuckDB may be installed in ../.python_deps.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import platform
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / ".python_deps"))
import duckdb

TABLES = ("region", "nation", "supplier", "customer", "part", "partsupp", "orders", "lineitem")
EXPECTED_SF1 = {
    "region": 5, "nation": 25, "supplier": 10000, "customer": 150000,
    "part": 200000, "partsupp": 800000, "orders": 1500000, "lineitem": 6001215,
}


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sf", type=float, default=1)
    parser.add_argument("--output", type=Path, default=ROOT / "data" / "tpch_sf1")
    args = parser.parse_args()
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s",
                        handlers=[logging.StreamHandler(), logging.FileHandler(output / "generation.log", encoding="utf-8")])
    started = datetime.now(timezone.utc)
    timer = time.perf_counter()
    logging.info("Generation begins: DuckDB=%s Python=%s sf=%s output=%s", duckdb.__version__, platform.python_version(), args.sf, output)
    db_path = output / "tpch.duckdb"
    con = duckdb.connect(str(db_path))
    con.execute("SET threads=4")
    con.execute("SET memory_limit='2GB'")
    con.execute("SET extension_directory=" + sql_literal(str(ROOT / ".duckdb_extensions")))
    con.execute("INSTALL tpch FROM core")
    con.execute("LOAD tpch")
    extension_result = con.execute("SELECT * FROM duckdb_extensions() WHERE extension_name='tpch'")
    extension_names = [column[0] for column in extension_result.description]
    extension = [dict(zip(extension_names, row)) for row in extension_result.fetchall()]
    logging.info("Extension metadata: %s", extension)
    if con.execute("SELECT count(*) FROM information_schema.tables WHERE table_schema='main'").fetchone()[0]:
        raise RuntimeError(f"Database already contains tables: {db_path}. Use a fresh output directory.")
    logging.info("Running CALL dbgen(sf=%s)", args.sf)
    con.execute("CALL dbgen(sf=?)", [args.sf])
    logging.info("dbgen completed after %.2f seconds", time.perf_counter() - timer)
    metadata = {
        "description": "TPC-H-derived educational data generated by DuckDB's official core tpch extension; not an official TPC-H benchmark result.",
        "source_urls": ["https://duckdb.org/docs/stable/core_extensions/tpch.html", "https://github.com/duckdb/duckdb/tree/v" + duckdb.__version__ + "/extension/tpch"],
        "duckdb_version": duckdb.__version__, "python_version": platform.python_version(),
        "platform": platform.platform(), "scale_factor": args.sf,
        "generation_command": f"CALL dbgen(sf={args.sf})", "extension": extension,
        "started_at_utc": started.isoformat(),
        "export_format": {"format": "CSV", "delimiter": "|", "header": False, "quote": '"', "escape": '"', "null": "\\N", "encoding": "UTF-8"},
        "tables": {},
    }
    ddl = []
    for table in TABLES:
        rows = con.execute(f"SELECT count(*) FROM {table}").fetchone()[0]
        if args.sf == 1 and rows != EXPECTED_SF1[table]:
            raise AssertionError(f"Unexpected SF=1 count for {table}: {rows}")
        columns = [dict(zip(("name", "type", "nullable"), row)) for row in con.execute(
            "SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema='main' AND table_name=? ORDER BY ordinal_position", [table]).fetchall()]
        sql = "CREATE TABLE " + table + " (\n" + ",\n".join("    " + c["name"] + " " + c["type"] + (" NOT NULL" if c["nullable"] == "NO" else "") for c in columns) + "\n);"
        ddl.append(sql)
        csv_path = output / f"{table}.csv"
        con.execute(f"COPY {table} TO {sql_literal(csv_path.as_posix())} (FORMAT CSV, DELIMITER '|', HEADER FALSE, NULL '\\N', QUOTE '\"', ESCAPE '\"')")
        digest = hashlib.sha256()
        with csv_path.open("rb") as handle:
            for block in iter(lambda: handle.read(8 * 1024 * 1024), b""):
                digest.update(block)
        metadata["tables"][table] = {"rows": rows, "columns": columns, "file": csv_path.name, "bytes": csv_path.stat().st_size, "sha256": digest.hexdigest()}
        logging.info("Exported %s: rows=%d bytes=%d sha256=%s", table, rows, csv_path.stat().st_size, digest.hexdigest())
    (output / "schema.sql").write_text("-- Generated from DuckDB information_schema. Compatible base types for PostgreSQL.\n-- Data-generation schema has no indexes or primary/foreign key constraints.\n\n" + "\n\n".join(ddl) + "\n", encoding="utf-8")
    con.execute("CHECKPOINT")
    con.close()
    metadata["completed_at_utc"] = datetime.now(timezone.utc).isoformat()
    metadata["elapsed_seconds"] = round(time.perf_counter() - timer, 3)
    (output / "metadata.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2, default=str) + "\n", encoding="utf-8")
    logging.info("Generation complete in %.2f seconds; metadata.json and schema.sql written.", metadata["elapsed_seconds"])


if __name__ == "__main__":
    main()
