-- The dedicated cardinality_lab database only. TPC-H primary/foreign keys and selected join indexes.
SET search_path=tpch;
ALTER TABLE region ADD PRIMARY KEY (r_regionkey);
ALTER TABLE nation ADD PRIMARY KEY (n_nationkey);
ALTER TABLE supplier ADD PRIMARY KEY (s_suppkey);
ALTER TABLE customer ADD PRIMARY KEY (c_custkey);
ALTER TABLE part ADD PRIMARY KEY (p_partkey);
ALTER TABLE partsupp ADD PRIMARY KEY (ps_partkey,ps_suppkey);
ALTER TABLE orders ADD PRIMARY KEY (o_orderkey);
ALTER TABLE lineitem ADD PRIMARY KEY (l_orderkey,l_linenumber);
ALTER TABLE nation ADD FOREIGN KEY (n_regionkey) REFERENCES region;
ALTER TABLE supplier ADD FOREIGN KEY (s_nationkey) REFERENCES nation;
ALTER TABLE customer ADD FOREIGN KEY (c_nationkey) REFERENCES nation;
ALTER TABLE partsupp ADD FOREIGN KEY (ps_partkey) REFERENCES part;
ALTER TABLE partsupp ADD FOREIGN KEY (ps_suppkey) REFERENCES supplier;
ALTER TABLE orders ADD FOREIGN KEY (o_custkey) REFERENCES customer;
ALTER TABLE lineitem ADD FOREIGN KEY (l_orderkey) REFERENCES orders;
ALTER TABLE lineitem ADD FOREIGN KEY (l_partkey,l_suppkey) REFERENCES partsupp;
CREATE INDEX orders_customer_idx ON orders(o_custkey);
CREATE INDEX lineitem_part_supplier_idx ON lineitem(l_partkey,l_suppkey);
ANALYZE;
